# Generated by Django 3.2.13 on 2022-05-18 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=20)),
                ('available_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
