# Generated by Django 3.2.13 on 2022-05-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
