# Generated by Django 3.2.13 on 2022-05-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='available_points',
            new_name='initial_points',
        ),
    ]
